version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile  
    tty: true
    stdin_open: true
    ports:
      - 8002:8002  
      - 3003:3003 
    command:
      sh -c "sleep 5 && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8002"  
    depends_on:
      -  db_vinted
    volumes:
      - .:/src

  db_vinted:
    image: postgres:10
    container_name: "db_vinted"
    env_file:
        - .env
    environment:
        POSTGRES_USER: $DBUSER
        POSTGRES_PASSWORD: $DBPASSWORD
    ports:
      - 5433:5432  
    volumes:
          - ./data:/var/lib/postgresql/data