# Generated by Django 2.2.3 on 2019-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdwordsAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField(blank=True, null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('adgroup_name', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('local_date', models.DateField()),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('media_source', models.TextField(blank=True, null=True)),
                ('portal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adwords_api',
            },
        ),
        migrations.CreateModel(
            name='SmartlyAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField(blank=True, null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('adgroup_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('fb_objective', models.TextField(blank=True, null=True)),
                ('local_date', models.DateField()),
                ('campaign_start_date', models.DateTimeField()),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('portal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'smartly_api',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('age_at_registration', models.IntegerField(blank=True, null=True)),
                ('registration_platform', models.TextField(blank=True, null=True)),
                ('registration_local_time', models.DateTimeField(blank=True, null=True)),
                ('first_visit_local_time', models.DateTimeField(blank=True, null=True)),
                ('first_listing_local_time', models.DateTimeField(blank=True, null=True)),
                ('first_sale_local_time', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_local_time', models.DateTimeField(blank=True, null=True)),
                ('registration_full_utm', models.TextField(blank=True, null=True)),
                ('first_visit_full_utm', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
