# Generated by Django 2.2.3 on 2019-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted_backend', '0002_userscampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscampaign',
            name='campaign_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
